import { ToastContainer } from "./nexttoast";
import 'react-toastify/dist/ReactToastify.css'; 
import "./globals.css";
import AuthProvider from "./component/AuthProvider/AuthProvider";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body suppressHydrationWarning={true}>
      <AuthProvider>
      {children}

      <ToastContainer />
      </AuthProvider>

    </body>


    </html>
  );
}
